apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea
  namespace: myapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicea
  template:
    metadata:
      labels:
        app: servicea
    spec:
      containers:
      - name: servicea
        image: mayupdocker/app-servicea:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: servicea
  namespace: myapp1
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: '8080'
spec:
  selector:
    app: servicea
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
