apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea
  namespace: myapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicea
  template:
    metadata:
      labels:
        app: servicea
    spec:
      containers:
      - name: servicea
        image: mayupdocker/app-servicea:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: servicea
  namespace: myapp1
spec:
  selector:
    app: servicea
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
